/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  APIResponse,
} from '../models';
import {
    APIResponseFromJSON,
    APIResponseToJSON,
} from '../models';

export interface InstancesInstanceKeyBusinessCatalogGetRequest {
    instanceKey: string;
}

/**
 * 
 */
export class BusinessManagementApi extends runtime.BaseAPI {

    /**
     * Gets list of all products registered by you.
     * Fetches the catlog.
     */
    async instancesInstanceKeyBusinessCatalogGetRaw(requestParameters: InstancesInstanceKeyBusinessCatalogGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<APIResponse>> {
        if (requestParameters.instanceKey === null || requestParameters.instanceKey === undefined) {
            throw new runtime.RequiredError('instanceKey','Required parameter requestParameters.instanceKey was null or undefined when calling instancesInstanceKeyBusinessCatalogGet.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/instances/{instance_key}/business/catalog`.replace(`{${"instance_key"}}`, encodeURIComponent(String(requestParameters.instanceKey))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => APIResponseFromJSON(jsonValue));
    }

    /**
     * Gets list of all products registered by you.
     * Fetches the catlog.
     */
    async instancesInstanceKeyBusinessCatalogGet(requestParameters: InstancesInstanceKeyBusinessCatalogGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<APIResponse> {
        const response = await this.instancesInstanceKeyBusinessCatalogGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
