/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ReplyButton } from './ReplyButton';
import {
    ReplyButtonFromJSON,
    ReplyButtonFromJSONTyped,
    ReplyButtonToJSON,
} from './ReplyButton';

/**
 * 
 * @export
 * @interface ButtonMessagePayload
 */
export interface ButtonMessagePayload {
    /**
     * 
     * @type {Array<ReplyButton>}
     * @memberof ButtonMessagePayload
     */
    buttons?: Array<ReplyButton>;
    /**
     * 
     * @type {string}
     * @memberof ButtonMessagePayload
     */
    footerText?: string;
    /**
     * 
     * @type {string}
     * @memberof ButtonMessagePayload
     */
    headerText?: string;
    /**
     * 
     * @type {string}
     * @memberof ButtonMessagePayload
     */
    text?: string;
    /**
     * 
     * @type {string}
     * @memberof ButtonMessagePayload
     */
    to?: string;
}

/**
 * Check if a given object implements the ButtonMessagePayload interface.
 */
export function instanceOfButtonMessagePayload(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ButtonMessagePayloadFromJSON(json: any): ButtonMessagePayload {
    return ButtonMessagePayloadFromJSONTyped(json, false);
}

export function ButtonMessagePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ButtonMessagePayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'buttons': !exists(json, 'buttons') ? undefined : ((json['buttons'] as Array<any>).map(ReplyButtonFromJSON)),
        'footerText': !exists(json, 'footer_text') ? undefined : json['footer_text'],
        'headerText': !exists(json, 'header_text') ? undefined : json['header_text'],
        'text': !exists(json, 'text') ? undefined : json['text'],
        'to': !exists(json, 'to') ? undefined : json['to'],
    };
}

export function ButtonMessagePayloadToJSON(value?: ButtonMessagePayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'buttons': value.buttons === undefined ? undefined : ((value.buttons as Array<any>).map(ReplyButtonToJSON)),
        'footer_text': value.footerText,
        'header_text': value.headerText,
        'text': value.text,
        'to': value.to,
    };
}

