/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ContactMessagePayloadVcard } from './ContactMessagePayloadVcard';
import {
    ContactMessagePayloadVcardFromJSON,
    ContactMessagePayloadVcardFromJSONTyped,
    ContactMessagePayloadVcardToJSON,
} from './ContactMessagePayloadVcard';

/**
 * 
 * @export
 * @interface ContactMessagePayload
 */
export interface ContactMessagePayload {
    /**
     * 
     * @type {string}
     * @memberof ContactMessagePayload
     */
    to: string;
    /**
     * 
     * @type {ContactMessagePayloadVcard}
     * @memberof ContactMessagePayload
     */
    vcard: ContactMessagePayloadVcard;
}

/**
 * Check if a given object implements the ContactMessagePayload interface.
 */
export function instanceOfContactMessagePayload(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "to" in value;
    isInstance = isInstance && "vcard" in value;

    return isInstance;
}

export function ContactMessagePayloadFromJSON(json: any): ContactMessagePayload {
    return ContactMessagePayloadFromJSONTyped(json, false);
}

export function ContactMessagePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactMessagePayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'to': json['to'],
        'vcard': ContactMessagePayloadVcardFromJSON(json['vcard']),
    };
}

export function ContactMessagePayloadToJSON(value?: ContactMessagePayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'to': value.to,
        'vcard': ContactMessagePayloadVcardToJSON(value.vcard),
    };
}

