/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContactMessagePayloadVcard
 */
export interface ContactMessagePayloadVcard {
    /**
     * 
     * @type {string}
     * @memberof ContactMessagePayloadVcard
     */
    fullName?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactMessagePayloadVcard
     */
    organization?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactMessagePayloadVcard
     */
    phone?: string;
}

/**
 * Check if a given object implements the ContactMessagePayloadVcard interface.
 */
export function instanceOfContactMessagePayloadVcard(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ContactMessagePayloadVcardFromJSON(json: any): ContactMessagePayloadVcard {
    return ContactMessagePayloadVcardFromJSONTyped(json, false);
}

export function ContactMessagePayloadVcardFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactMessagePayloadVcard {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fullName': !exists(json, 'full_name') ? undefined : json['full_name'],
        'organization': !exists(json, 'organization') ? undefined : json['organization'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
    };
}

export function ContactMessagePayloadVcardToJSON(value?: ContactMessagePayloadVcard | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'full_name': value.fullName,
        'organization': value.organization,
        'phone': value.phone,
    };
}

