/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateInstancePayload
 */
export interface CreateInstancePayload {
    /**
     * 
     * @type {string}
     * @memberof CreateInstancePayload
     */
    instanceKey?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateInstancePayload
     */
    webhookUrl?: string;
}

/**
 * Check if a given object implements the CreateInstancePayload interface.
 */
export function instanceOfCreateInstancePayload(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateInstancePayloadFromJSON(json: any): CreateInstancePayload {
    return CreateInstancePayloadFromJSONTyped(json, false);
}

export function CreateInstancePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInstancePayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'instanceKey': !exists(json, 'instance_key') ? undefined : json['instance_key'],
        'webhookUrl': !exists(json, 'webhook_url') ? undefined : json['webhook_url'],
    };
}

export function CreateInstancePayloadToJSON(value?: CreateInstancePayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'instance_key': value.instanceKey,
        'webhook_url': value.webhookUrl,
    };
}

