/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupUpdateParticipantsPayload
 */
export interface GroupUpdateParticipantsPayload {
    /**
     * 
     * @type {Array<string>}
     * @memberof GroupUpdateParticipantsPayload
     */
    participants?: Array<string>;
}

/**
 * Check if a given object implements the GroupUpdateParticipantsPayload interface.
 */
export function instanceOfGroupUpdateParticipantsPayload(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GroupUpdateParticipantsPayloadFromJSON(json: any): GroupUpdateParticipantsPayload {
    return GroupUpdateParticipantsPayloadFromJSONTyped(json, false);
}

export function GroupUpdateParticipantsPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupUpdateParticipantsPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'participants': !exists(json, 'participants') ? undefined : json['participants'],
    };
}

export function GroupUpdateParticipantsPayloadToJSON(value?: GroupUpdateParticipantsPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'participants': value.participants,
    };
}

