/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupUpdateDescriptionPayload
 */
export interface GroupUpdateDescriptionPayload {
    /**
     * 
     * @type {string}
     * @memberof GroupUpdateDescriptionPayload
     */
    description?: string;
}

/**
 * Check if a given object implements the GroupUpdateDescriptionPayload interface.
 */
export function instanceOfGroupUpdateDescriptionPayload(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GroupUpdateDescriptionPayloadFromJSON(json: any): GroupUpdateDescriptionPayload {
    return GroupUpdateDescriptionPayloadFromJSONTyped(json, false);
}

export function GroupUpdateDescriptionPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupUpdateDescriptionPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function GroupUpdateDescriptionPayloadToJSON(value?: GroupUpdateDescriptionPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
    };
}

