/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupUpdateNamePayload
 */
export interface GroupUpdateNamePayload {
    /**
     * 
     * @type {string}
     * @memberof GroupUpdateNamePayload
     */
    name?: string;
}

/**
 * Check if a given object implements the GroupUpdateNamePayload interface.
 */
export function instanceOfGroupUpdateNamePayload(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GroupUpdateNamePayloadFromJSON(json: any): GroupUpdateNamePayload {
    return GroupUpdateNamePayloadFromJSONTyped(json, false);
}

export function GroupUpdateNamePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupUpdateNamePayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function GroupUpdateNamePayloadToJSON(value?: GroupUpdateNamePayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

