/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupInviteMessagePayload
 */
export interface GroupInviteMessagePayload {
    /**
     * 
     * @type {string}
     * @memberof GroupInviteMessagePayload
     */
    caption?: string;
    /**
     * 
     * @type {number}
     * @memberof GroupInviteMessagePayload
     */
    expiryMinutes?: number;
    /**
     * 
     * @type {string}
     * @memberof GroupInviteMessagePayload
     */
    inviteCode?: string;
    /**
     * 
     * @type {string}
     * @memberof GroupInviteMessagePayload
     */
    to?: string;
}

/**
 * Check if a given object implements the GroupInviteMessagePayload interface.
 */
export function instanceOfGroupInviteMessagePayload(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GroupInviteMessagePayloadFromJSON(json: any): GroupInviteMessagePayload {
    return GroupInviteMessagePayloadFromJSONTyped(json, false);
}

export function GroupInviteMessagePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupInviteMessagePayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'caption': !exists(json, 'caption') ? undefined : json['caption'],
        'expiryMinutes': !exists(json, 'expiry_minutes') ? undefined : json['expiry_minutes'],
        'inviteCode': !exists(json, 'invite_code') ? undefined : json['invite_code'],
        'to': !exists(json, 'to') ? undefined : json['to'],
    };
}

export function GroupInviteMessagePayloadToJSON(value?: GroupInviteMessagePayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'caption': value.caption,
        'expiry_minutes': value.expiryMinutes,
        'invite_code': value.inviteCode,
        'to': value.to,
    };
}

