/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstancesInstanceKeyGroupsGroupIdProfilePicPutRequest
 */
export interface InstancesInstanceKeyGroupsGroupIdProfilePicPutRequest {
    /**
     * Group picture in JPEG
     * @type {Blob}
     * @memberof InstancesInstanceKeyGroupsGroupIdProfilePicPutRequest
     */
    file: Blob;
}

/**
 * Check if a given object implements the InstancesInstanceKeyGroupsGroupIdProfilePicPutRequest interface.
 */
export function instanceOfInstancesInstanceKeyGroupsGroupIdProfilePicPutRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "file" in value;

    return isInstance;
}

export function InstancesInstanceKeyGroupsGroupIdProfilePicPutRequestFromJSON(json: any): InstancesInstanceKeyGroupsGroupIdProfilePicPutRequest {
    return InstancesInstanceKeyGroupsGroupIdProfilePicPutRequestFromJSONTyped(json, false);
}

export function InstancesInstanceKeyGroupsGroupIdProfilePicPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstancesInstanceKeyGroupsGroupIdProfilePicPutRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'file': json['file'],
    };
}

export function InstancesInstanceKeyGroupsGroupIdProfilePicPutRequestToJSON(value?: InstancesInstanceKeyGroupsGroupIdProfilePicPutRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'file': value.file,
    };
}

