/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstancesInstanceKeySendUploadPostRequest
 */
export interface InstancesInstanceKeySendUploadPostRequest {
    /**
     * Media file
     * @type {Blob}
     * @memberof InstancesInstanceKeySendUploadPostRequest
     */
    file: Blob;
}

/**
 * Check if a given object implements the InstancesInstanceKeySendUploadPostRequest interface.
 */
export function instanceOfInstancesInstanceKeySendUploadPostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "file" in value;

    return isInstance;
}

export function InstancesInstanceKeySendUploadPostRequestFromJSON(json: any): InstancesInstanceKeySendUploadPostRequest {
    return InstancesInstanceKeySendUploadPostRequestFromJSONTyped(json, false);
}

export function InstancesInstanceKeySendUploadPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstancesInstanceKeySendUploadPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'file': json['file'],
    };
}

export function InstancesInstanceKeySendUploadPostRequestToJSON(value?: InstancesInstanceKeySendUploadPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'file': value.file,
    };
}

