/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstancesInstanceKeySendDocumentPostRequest
 */
export interface InstancesInstanceKeySendDocumentPostRequest {
    /**
     * Document file
     * @type {Blob}
     * @memberof InstancesInstanceKeySendDocumentPostRequest
     */
    file: Blob;
}

/**
 * Check if a given object implements the InstancesInstanceKeySendDocumentPostRequest interface.
 */
export function instanceOfInstancesInstanceKeySendDocumentPostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "file" in value;

    return isInstance;
}

export function InstancesInstanceKeySendDocumentPostRequestFromJSON(json: any): InstancesInstanceKeySendDocumentPostRequest {
    return InstancesInstanceKeySendDocumentPostRequestFromJSONTyped(json, false);
}

export function InstancesInstanceKeySendDocumentPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstancesInstanceKeySendDocumentPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'file': json['file'],
    };
}

export function InstancesInstanceKeySendDocumentPostRequestToJSON(value?: InstancesInstanceKeySendDocumentPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'file': value.file,
    };
}

