/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstancesInstanceKeySendVideoPostRequest
 */
export interface InstancesInstanceKeySendVideoPostRequest {
    /**
     * Video file
     * @type {Blob}
     * @memberof InstancesInstanceKeySendVideoPostRequest
     */
    file: Blob;
}

/**
 * Check if a given object implements the InstancesInstanceKeySendVideoPostRequest interface.
 */
export function instanceOfInstancesInstanceKeySendVideoPostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "file" in value;

    return isInstance;
}

export function InstancesInstanceKeySendVideoPostRequestFromJSON(json: any): InstancesInstanceKeySendVideoPostRequest {
    return InstancesInstanceKeySendVideoPostRequestFromJSONTyped(json, false);
}

export function InstancesInstanceKeySendVideoPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstancesInstanceKeySendVideoPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'file': json['file'],
    };
}

export function InstancesInstanceKeySendVideoPostRequestToJSON(value?: InstancesInstanceKeySendVideoPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'file': value.file,
    };
}

