/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstancesInstanceKeySendImagePostRequest
 */
export interface InstancesInstanceKeySendImagePostRequest {
    /**
     * Image file
     * @type {Blob}
     * @memberof InstancesInstanceKeySendImagePostRequest
     */
    file: Blob;
}

/**
 * Check if a given object implements the InstancesInstanceKeySendImagePostRequest interface.
 */
export function instanceOfInstancesInstanceKeySendImagePostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "file" in value;

    return isInstance;
}

export function InstancesInstanceKeySendImagePostRequestFromJSON(json: any): InstancesInstanceKeySendImagePostRequest {
    return InstancesInstanceKeySendImagePostRequestFromJSONTyped(json, false);
}

export function InstancesInstanceKeySendImagePostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstancesInstanceKeySendImagePostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'file': json['file'],
    };
}

export function InstancesInstanceKeySendImagePostRequestToJSON(value?: InstancesInstanceKeySendImagePostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'file': value.file,
    };
}

