/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InstancesInstanceKeySendAudioPostRequest
 */
export interface InstancesInstanceKeySendAudioPostRequest {
    /**
     * Audio file
     * @type {Blob}
     * @memberof InstancesInstanceKeySendAudioPostRequest
     */
    file: Blob;
}

/**
 * Check if a given object implements the InstancesInstanceKeySendAudioPostRequest interface.
 */
export function instanceOfInstancesInstanceKeySendAudioPostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "file" in value;

    return isInstance;
}

export function InstancesInstanceKeySendAudioPostRequestFromJSON(json: any): InstancesInstanceKeySendAudioPostRequest {
    return InstancesInstanceKeySendAudioPostRequestFromJSONTyped(json, false);
}

export function InstancesInstanceKeySendAudioPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstancesInstanceKeySendAudioPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'file': json['file'],
    };
}

export function InstancesInstanceKeySendAudioPostRequestToJSON(value?: InstancesInstanceKeySendAudioPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'file': value.file,
    };
}

