/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListItem
 */
export interface ListItem {
    /**
     * 
     * @type {string}
     * @memberof ListItem
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ListItem
     */
    rowId?: string;
    /**
     * 
     * @type {string}
     * @memberof ListItem
     */
    title: string;
}

/**
 * Check if a given object implements the ListItem interface.
 */
export function instanceOfListItem(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;

    return isInstance;
}

export function ListItemFromJSON(json: any): ListItem {
    return ListItemFromJSONTyped(json, false);
}

export function ListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
        'rowId': !exists(json, 'row_id') ? undefined : json['row_id'],
        'title': json['title'],
    };
}

export function ListItemToJSON(value?: ListItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
        'row_id': value.rowId,
        'title': value.title,
    };
}

