/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ListItem } from './ListItem';
import {
    ListItemFromJSON,
    ListItemFromJSONTyped,
    ListItemToJSON,
} from './ListItem';

/**
 * 
 * @export
 * @interface ListSection
 */
export interface ListSection {
    /**
     * 
     * @type {Array<ListItem>}
     * @memberof ListSection
     */
    rows: Array<ListItem>;
    /**
     * 
     * @type {string}
     * @memberof ListSection
     */
    title: string;
}

/**
 * Check if a given object implements the ListSection interface.
 */
export function instanceOfListSection(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "rows" in value;
    isInstance = isInstance && "title" in value;

    return isInstance;
}

export function ListSectionFromJSON(json: any): ListSection {
    return ListSectionFromJSONTyped(json, false);
}

export function ListSectionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListSection {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rows': ((json['rows'] as Array<any>).map(ListItemFromJSON)),
        'title': json['title'],
    };
}

export function ListSectionToJSON(value?: ListSection | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'rows': ((value.rows as Array<any>).map(ListItemToJSON)),
        'title': value.title,
    };
}

