/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MainAPIResponse
 */
export interface MainAPIResponse {
    /**
     * 
     * @type {object}
     * @memberof MainAPIResponse
     */
    data?: object;
    /**
     * 
     * @type {boolean}
     * @memberof MainAPIResponse
     */
    error?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MainAPIResponse
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof MainAPIResponse
     */
    status?: number;
}

/**
 * Check if a given object implements the MainAPIResponse interface.
 */
export function instanceOfMainAPIResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MainAPIResponseFromJSON(json: any): MainAPIResponse {
    return MainAPIResponseFromJSONTyped(json, false);
}

export function MainAPIResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MainAPIResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': !exists(json, 'data') ? undefined : json['data'],
        'error': !exists(json, 'error') ? undefined : json['error'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'status': !exists(json, 'status') ? undefined : json['status'],
    };
}

export function MainAPIResponseToJSON(value?: MainAPIResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data,
        'error': value.error,
        'message': value.message,
        'status': value.status,
    };
}

