/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaymentRequestPayload
 */
export interface PaymentRequestPayload {
    /**
     * 
     * @type {number}
     * @memberof PaymentRequestPayload
     */
    amount?: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequestPayload
     */
    currency?: string;
    /**
     * 
     * @type {number}
     * @memberof PaymentRequestPayload
     */
    expiryMinutes?: number;
    /**
     * 
     * @type {string}
     * @memberof PaymentRequestPayload
     */
    to?: string;
}

/**
 * Check if a given object implements the PaymentRequestPayload interface.
 */
export function instanceOfPaymentRequestPayload(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaymentRequestPayloadFromJSON(json: any): PaymentRequestPayload {
    return PaymentRequestPayloadFromJSONTyped(json, false);
}

export function PaymentRequestPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaymentRequestPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'amount': !exists(json, 'amount') ? undefined : json['amount'],
        'currency': !exists(json, 'currency') ? undefined : json['currency'],
        'expiryMinutes': !exists(json, 'expiry_minutes') ? undefined : json['expiry_minutes'],
        'to': !exists(json, 'to') ? undefined : json['to'],
    };
}

export function PaymentRequestPayloadToJSON(value?: PaymentRequestPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'amount': value.amount,
        'currency': value.currency,
        'expiry_minutes': value.expiryMinutes,
        'to': value.to,
    };
}

