/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PollMessagePayload
 */
export interface PollMessagePayload {
    /**
     * 
     * @type {Array<string>}
     * @memberof PollMessagePayload
     */
    options: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof PollMessagePayload
     */
    selectableOptionsCount: number;
    /**
     * 
     * @type {string}
     * @memberof PollMessagePayload
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof PollMessagePayload
     */
    to: string;
}

/**
 * Check if a given object implements the PollMessagePayload interface.
 */
export function instanceOfPollMessagePayload(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "options" in value;
    isInstance = isInstance && "selectableOptionsCount" in value;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "to" in value;

    return isInstance;
}

export function PollMessagePayloadFromJSON(json: any): PollMessagePayload {
    return PollMessagePayloadFromJSONTyped(json, false);
}

export function PollMessagePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): PollMessagePayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'options': json['options'],
        'selectableOptionsCount': json['selectable_options_count'],
        'title': json['title'],
        'to': json['to'],
    };
}

export function PollMessagePayloadToJSON(value?: PollMessagePayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'options': value.options,
        'selectable_options_count': value.selectableOptionsCount,
        'title': value.title,
        'to': value.to,
    };
}

