/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendVideoRequest
 */
export interface SendVideoRequest {
    /**
     * Video file
     * @type {Blob}
     * @memberof SendVideoRequest
     */
    file: Blob;
}

/**
 * Check if a given object implements the SendVideoRequest interface.
 */
export function instanceOfSendVideoRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "file" in value;

    return isInstance;
}

export function SendVideoRequestFromJSON(json: any): SendVideoRequest {
    return SendVideoRequestFromJSONTyped(json, false);
}

export function SendVideoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendVideoRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'file': json['file'],
    };
}

export function SendVideoRequestToJSON(value?: SendVideoRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'file': value.file,
    };
}

