/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendDocumentRequest
 */
export interface SendDocumentRequest {
    /**
     * Document file
     * @type {Blob}
     * @memberof SendDocumentRequest
     */
    file: Blob;
}

/**
 * Check if a given object implements the SendDocumentRequest interface.
 */
export function instanceOfSendDocumentRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "file" in value;

    return isInstance;
}

export function SendDocumentRequestFromJSON(json: any): SendDocumentRequest {
    return SendDocumentRequestFromJSONTyped(json, false);
}

export function SendDocumentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendDocumentRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'file': json['file'],
    };
}

export function SendDocumentRequestToJSON(value?: SendDocumentRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'file': value.file,
    };
}

