/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendImageRequest
 */
export interface SendImageRequest {
    /**
     * Image file
     * @type {Blob}
     * @memberof SendImageRequest
     */
    file: Blob;
}

/**
 * Check if a given object implements the SendImageRequest interface.
 */
export function instanceOfSendImageRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "file" in value;

    return isInstance;
}

export function SendImageRequestFromJSON(json: any): SendImageRequest {
    return SendImageRequestFromJSONTyped(json, false);
}

export function SendImageRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendImageRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'file': json['file'],
    };
}

export function SendImageRequestToJSON(value?: SendImageRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'file': value.file,
    };
}

