/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetGroupPictureRequest
 */
export interface SetGroupPictureRequest {
    /**
     * Group picture in JPEG
     * @type {Blob}
     * @memberof SetGroupPictureRequest
     */
    file: Blob;
}

/**
 * Check if a given object implements the SetGroupPictureRequest interface.
 */
export function instanceOfSetGroupPictureRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "file" in value;

    return isInstance;
}

export function SetGroupPictureRequestFromJSON(json: any): SetGroupPictureRequest {
    return SetGroupPictureRequestFromJSONTyped(json, false);
}

export function SetGroupPictureRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetGroupPictureRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'file': json['file'],
    };
}

export function SetGroupPictureRequestToJSON(value?: SetGroupPictureRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'file': value.file,
    };
}

