/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StructsLocationMessagePayloadLocation
 */
export interface StructsLocationMessagePayloadLocation {
    /**
     * 
     * @type {string}
     * @memberof StructsLocationMessagePayloadLocation
     */
    address?: string;
    /**
     * 
     * @type {number}
     * @memberof StructsLocationMessagePayloadLocation
     */
    latitude: number;
    /**
     * 
     * @type {number}
     * @memberof StructsLocationMessagePayloadLocation
     */
    longitude: number;
    /**
     * 
     * @type {string}
     * @memberof StructsLocationMessagePayloadLocation
     */
    name: string;
}

/**
 * Check if a given object implements the StructsLocationMessagePayloadLocation interface.
 */
export function instanceOfStructsLocationMessagePayloadLocation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "latitude" in value;
    isInstance = isInstance && "longitude" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function StructsLocationMessagePayloadLocationFromJSON(json: any): StructsLocationMessagePayloadLocation {
    return StructsLocationMessagePayloadLocationFromJSONTyped(json, false);
}

export function StructsLocationMessagePayloadLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): StructsLocationMessagePayloadLocation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': !exists(json, 'address') ? undefined : json['address'],
        'latitude': json['latitude'],
        'longitude': json['longitude'],
        'name': json['name'],
    };
}

export function StructsLocationMessagePayloadLocationToJSON(value?: StructsLocationMessagePayloadLocation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': value.address,
        'latitude': value.latitude,
        'longitude': value.longitude,
        'name': value.name,
    };
}

