/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StructsTemplateButton } from './StructsTemplateButton';
import {
    StructsTemplateButtonFromJSON,
    StructsTemplateButtonFromJSONTyped,
    StructsTemplateButtonToJSON,
} from './StructsTemplateButton';

/**
 * 
 * @export
 * @interface StructsTemplateButtonPayload
 */
export interface StructsTemplateButtonPayload {
    /**
     * 
     * @type {Array<StructsTemplateButton>}
     * @memberof StructsTemplateButtonPayload
     */
    buttons: Array<StructsTemplateButton>;
    /**
     * 
     * @type {string}
     * @memberof StructsTemplateButtonPayload
     */
    contentText?: string;
    /**
     * 
     * @type {string}
     * @memberof StructsTemplateButtonPayload
     */
    footer?: string;
    /**
     * 
     * @type {string}
     * @memberof StructsTemplateButtonPayload
     */
    header?: string;
    /**
     * 
     * @type {string}
     * @memberof StructsTemplateButtonPayload
     */
    to: string;
}

/**
 * Check if a given object implements the StructsTemplateButtonPayload interface.
 */
export function instanceOfStructsTemplateButtonPayload(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "buttons" in value;
    isInstance = isInstance && "to" in value;

    return isInstance;
}

export function StructsTemplateButtonPayloadFromJSON(json: any): StructsTemplateButtonPayload {
    return StructsTemplateButtonPayloadFromJSONTyped(json, false);
}

export function StructsTemplateButtonPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): StructsTemplateButtonPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'buttons': ((json['buttons'] as Array<any>).map(StructsTemplateButtonFromJSON)),
        'contentText': !exists(json, 'content_text') ? undefined : json['content_text'],
        'footer': !exists(json, 'footer') ? undefined : json['footer'],
        'header': !exists(json, 'header') ? undefined : json['header'],
        'to': json['to'],
    };
}

export function StructsTemplateButtonPayloadToJSON(value?: StructsTemplateButtonPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'buttons': ((value.buttons as Array<any>).map(StructsTemplateButtonToJSON)),
        'content_text': value.contentText,
        'footer': value.footer,
        'header': value.header,
        'to': value.to,
    };
}

