/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StructsGroupUpdateNamePayload
 */
export interface StructsGroupUpdateNamePayload {
    /**
     * 
     * @type {string}
     * @memberof StructsGroupUpdateNamePayload
     */
    name?: string;
}

/**
 * Check if a given object implements the StructsGroupUpdateNamePayload interface.
 */
export function instanceOfStructsGroupUpdateNamePayload(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StructsGroupUpdateNamePayloadFromJSON(json: any): StructsGroupUpdateNamePayload {
    return StructsGroupUpdateNamePayloadFromJSONTyped(json, false);
}

export function StructsGroupUpdateNamePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): StructsGroupUpdateNamePayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function StructsGroupUpdateNamePayloadToJSON(value?: StructsGroupUpdateNamePayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

