/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StructsFileUpload } from './StructsFileUpload';
import {
    StructsFileUploadFromJSON,
    StructsFileUploadFromJSONTyped,
    StructsFileUploadToJSON,
} from './StructsFileUpload';
import type { StructsReplyButton } from './StructsReplyButton';
import {
    StructsReplyButtonFromJSON,
    StructsReplyButtonFromJSONTyped,
    StructsReplyButtonToJSON,
} from './StructsReplyButton';

/**
 * 
 * @export
 * @interface StructsButtonMessageWithMediaPayload
 */
export interface StructsButtonMessageWithMediaPayload {
    /**
     * 
     * @type {Array<StructsReplyButton>}
     * @memberof StructsButtonMessageWithMediaPayload
     */
    buttons?: Array<StructsReplyButton>;
    /**
     * 
     * @type {string}
     * @memberof StructsButtonMessageWithMediaPayload
     */
    footerText?: string;
    /**
     * 
     * @type {StructsFileUpload}
     * @memberof StructsButtonMessageWithMediaPayload
     */
    mediaData?: StructsFileUpload;
    /**
     * 
     * @type {string}
     * @memberof StructsButtonMessageWithMediaPayload
     */
    text?: string;
    /**
     * 
     * @type {string}
     * @memberof StructsButtonMessageWithMediaPayload
     */
    to?: string;
}

/**
 * Check if a given object implements the StructsButtonMessageWithMediaPayload interface.
 */
export function instanceOfStructsButtonMessageWithMediaPayload(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StructsButtonMessageWithMediaPayloadFromJSON(json: any): StructsButtonMessageWithMediaPayload {
    return StructsButtonMessageWithMediaPayloadFromJSONTyped(json, false);
}

export function StructsButtonMessageWithMediaPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): StructsButtonMessageWithMediaPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'buttons': !exists(json, 'buttons') ? undefined : ((json['buttons'] as Array<any>).map(StructsReplyButtonFromJSON)),
        'footerText': !exists(json, 'footer_text') ? undefined : json['footer_text'],
        'mediaData': !exists(json, 'media_data') ? undefined : StructsFileUploadFromJSON(json['media_data']),
        'text': !exists(json, 'text') ? undefined : json['text'],
        'to': !exists(json, 'to') ? undefined : json['to'],
    };
}

export function StructsButtonMessageWithMediaPayloadToJSON(value?: StructsButtonMessageWithMediaPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'buttons': value.buttons === undefined ? undefined : ((value.buttons as Array<any>).map(StructsReplyButtonToJSON)),
        'footer_text': value.footerText,
        'media_data': StructsFileUploadToJSON(value.mediaData),
        'text': value.text,
        'to': value.to,
    };
}

