/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StructsReplyButton
 */
export interface StructsReplyButton {
    /**
     * 
     * @type {string}
     * @memberof StructsReplyButton
     */
    buttonId?: string;
    /**
     * 
     * @type {string}
     * @memberof StructsReplyButton
     */
    buttonText?: string;
}

/**
 * Check if a given object implements the StructsReplyButton interface.
 */
export function instanceOfStructsReplyButton(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StructsReplyButtonFromJSON(json: any): StructsReplyButton {
    return StructsReplyButtonFromJSONTyped(json, false);
}

export function StructsReplyButtonFromJSONTyped(json: any, ignoreDiscriminator: boolean): StructsReplyButton {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'buttonId': !exists(json, 'button_id') ? undefined : json['button_id'],
        'buttonText': !exists(json, 'button_text') ? undefined : json['button_text'],
    };
}

export function StructsReplyButtonToJSON(value?: StructsReplyButton | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'button_id': value.buttonId,
        'button_text': value.buttonText,
    };
}

