/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StructsWebhookPayload
 */
export interface StructsWebhookPayload {
    /**
     * 
     * @type {string}
     * @memberof StructsWebhookPayload
     */
    webhookUrl?: string;
}

/**
 * Check if a given object implements the StructsWebhookPayload interface.
 */
export function instanceOfStructsWebhookPayload(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StructsWebhookPayloadFromJSON(json: any): StructsWebhookPayload {
    return StructsWebhookPayloadFromJSONTyped(json, false);
}

export function StructsWebhookPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): StructsWebhookPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'webhookUrl': !exists(json, 'webhook_url') ? undefined : json['webhook_url'],
    };
}

export function StructsWebhookPayloadToJSON(value?: StructsWebhookPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'webhook_url': value.webhookUrl,
    };
}

