/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StructsGroupCreatePayload
 */
export interface StructsGroupCreatePayload {
    /**
     * 
     * @type {string}
     * @memberof StructsGroupCreatePayload
     */
    groupName?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof StructsGroupCreatePayload
     */
    participants?: Array<string>;
}

/**
 * Check if a given object implements the StructsGroupCreatePayload interface.
 */
export function instanceOfStructsGroupCreatePayload(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StructsGroupCreatePayloadFromJSON(json: any): StructsGroupCreatePayload {
    return StructsGroupCreatePayloadFromJSONTyped(json, false);
}

export function StructsGroupCreatePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): StructsGroupCreatePayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'groupName': !exists(json, 'group_name') ? undefined : json['group_name'],
        'participants': !exists(json, 'participants') ? undefined : json['participants'],
    };
}

export function StructsGroupCreatePayloadToJSON(value?: StructsGroupCreatePayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'group_name': value.groupName,
        'participants': value.participants,
    };
}

