/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StructsGroupUpdateDescriptionPayload
 */
export interface StructsGroupUpdateDescriptionPayload {
    /**
     * 
     * @type {string}
     * @memberof StructsGroupUpdateDescriptionPayload
     */
    description?: string;
}

/**
 * Check if a given object implements the StructsGroupUpdateDescriptionPayload interface.
 */
export function instanceOfStructsGroupUpdateDescriptionPayload(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StructsGroupUpdateDescriptionPayloadFromJSON(json: any): StructsGroupUpdateDescriptionPayload {
    return StructsGroupUpdateDescriptionPayloadFromJSONTyped(json, false);
}

export function StructsGroupUpdateDescriptionPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): StructsGroupUpdateDescriptionPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function StructsGroupUpdateDescriptionPayloadToJSON(value?: StructsGroupUpdateDescriptionPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'description': value.description,
    };
}

