/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TemplateButton
 */
export interface TemplateButton {
    /**
     * Make sure this is unique
     * @type {string}
     * @memberof TemplateButton
     */
    buttonId?: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateButton
     */
    payload?: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateButton
     */
    title: string;
    /**
     * Valid types are replyButton, urlButton & callButton
     * @type {string}
     * @memberof TemplateButton
     */
    type: string;
}

/**
 * Check if a given object implements the TemplateButton interface.
 */
export function instanceOfTemplateButton(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function TemplateButtonFromJSON(json: any): TemplateButton {
    return TemplateButtonFromJSONTyped(json, false);
}

export function TemplateButtonFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateButton {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'buttonId': !exists(json, 'button_id') ? undefined : json['button_id'],
        'payload': !exists(json, 'payload') ? undefined : json['payload'],
        'title': json['title'],
        'type': json['type'],
    };
}

export function TemplateButtonToJSON(value?: TemplateButton | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'button_id': value.buttonId,
        'payload': value.payload,
        'title': value.title,
        'type': value.type,
    };
}

