/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FileUpload } from './FileUpload';
import {
    FileUploadFromJSON,
    FileUploadFromJSONTyped,
    FileUploadToJSON,
} from './FileUpload';
import type { TemplateButton } from './TemplateButton';
import {
    TemplateButtonFromJSON,
    TemplateButtonFromJSONTyped,
    TemplateButtonToJSON,
} from './TemplateButton';

/**
 * 
 * @export
 * @interface TemplateButtonWithMediaPayload
 */
export interface TemplateButtonWithMediaPayload {
    /**
     * 
     * @type {Array<TemplateButton>}
     * @memberof TemplateButtonWithMediaPayload
     */
    buttons: Array<TemplateButton>;
    /**
     * 
     * @type {string}
     * @memberof TemplateButtonWithMediaPayload
     */
    contentText?: string;
    /**
     * 
     * @type {string}
     * @memberof TemplateButtonWithMediaPayload
     */
    footer?: string;
    /**
     * 
     * @type {FileUpload}
     * @memberof TemplateButtonWithMediaPayload
     */
    media: FileUpload;
    /**
     * 
     * @type {string}
     * @memberof TemplateButtonWithMediaPayload
     */
    to: string;
}

/**
 * Check if a given object implements the TemplateButtonWithMediaPayload interface.
 */
export function instanceOfTemplateButtonWithMediaPayload(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "buttons" in value;
    isInstance = isInstance && "media" in value;
    isInstance = isInstance && "to" in value;

    return isInstance;
}

export function TemplateButtonWithMediaPayloadFromJSON(json: any): TemplateButtonWithMediaPayload {
    return TemplateButtonWithMediaPayloadFromJSONTyped(json, false);
}

export function TemplateButtonWithMediaPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): TemplateButtonWithMediaPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'buttons': ((json['buttons'] as Array<any>).map(TemplateButtonFromJSON)),
        'contentText': !exists(json, 'content_text') ? undefined : json['content_text'],
        'footer': !exists(json, 'footer') ? undefined : json['footer'],
        'media': FileUploadFromJSON(json['media']),
        'to': json['to'],
    };
}

export function TemplateButtonWithMediaPayloadToJSON(value?: TemplateButtonWithMediaPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'buttons': ((value.buttons as Array<any>).map(TemplateButtonToJSON)),
        'content_text': value.contentText,
        'footer': value.footer,
        'media': FileUploadToJSON(value.media),
        'to': value.to,
    };
}

