/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProfilePicRequest
 */
export interface UpdateProfilePicRequest {
    /**
     * Image file
     * @type {Blob}
     * @memberof UpdateProfilePicRequest
     */
    file: Blob;
}

/**
 * Check if a given object implements the UpdateProfilePicRequest interface.
 */
export function instanceOfUpdateProfilePicRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "file" in value;

    return isInstance;
}

export function UpdateProfilePicRequestFromJSON(json: any): UpdateProfilePicRequest {
    return UpdateProfilePicRequestFromJSONTyped(json, false);
}

export function UpdateProfilePicRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProfilePicRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'file': json['file'],
    };
}

export function UpdateProfilePicRequestToJSON(value?: UpdateProfilePicRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'file': value.file,
    };
}

