/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UrlMediaUploadPayload
 */
export interface UrlMediaUploadPayload {
    /**
     * 
     * @type {string}
     * @memberof UrlMediaUploadPayload
     */
    url?: string;
}

/**
 * Check if a given object implements the UrlMediaUploadPayload interface.
 */
export function instanceOfUrlMediaUploadPayload(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UrlMediaUploadPayloadFromJSON(json: any): UrlMediaUploadPayload {
    return UrlMediaUploadPayloadFromJSONTyped(json, false);
}

export function UrlMediaUploadPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): UrlMediaUploadPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function UrlMediaUploadPayloadToJSON(value?: UrlMediaUploadPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
    };
}

