/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserInfoPayload
 */
export interface UserInfoPayload {
    /**
     * 
     * @type {Array<string>}
     * @memberof UserInfoPayload
     */
    userIds: Array<string>;
}

/**
 * Check if a given object implements the UserInfoPayload interface.
 */
export function instanceOfUserInfoPayload(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userIds" in value;

    return isInstance;
}

export function UserInfoPayloadFromJSON(json: any): UserInfoPayload {
    return UserInfoPayloadFromJSONTyped(json, false);
}

export function UserInfoPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserInfoPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userIds': json['user_ids'],
    };
}

export function UserInfoPayloadToJSON(value?: UserInfoPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user_ids': value.userIds,
    };
}

