/* tslint:disable */
/* eslint-disable */
/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookPayload
 */
export interface WebhookPayload {
    /**
     * 
     * @type {string}
     * @memberof WebhookPayload
     */
    webhookUrl?: string;
}

/**
 * Check if a given object implements the WebhookPayload interface.
 */
export function instanceOfWebhookPayload(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function WebhookPayloadFromJSON(json: any): WebhookPayload {
    return WebhookPayloadFromJSONTyped(json, false);
}

export function WebhookPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'webhookUrl': !exists(json, 'webhook_url') ? undefined : json['webhook_url'],
    };
}

export function WebhookPayloadToJSON(value?: WebhookPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'webhook_url': value.webhookUrl,
    };
}

